### ISSUE TITLE
UnnecessaryAsync warning for a method involving using expression statements

### ISSUE THREAD

**Issue by semihokur** [semihokur/AsyncFixer#1]
```   
async Task foo()
{
    MemoryStream destination = new MemoryStream();
    using FileStream source = File.Open("data", FileMode.Open);
    await source.CopyToAsync(destination);
}
```

AsyncFixer currently gives a warning to remove async/await keywords in the method below. It suggests replacing the last statement with:
`return source.CopyToAsync(destination);`
However, this can cause an exception if `CopyToAsync` takes slightly longer because the operation will continue with the disposed `source` object.

**Comment by afelinczak** [comment]
Hey @semihokur,
Thanks for awesome plugin. 
Sadly I still getting very similar issue in 1.5.1
Using Jaeger and open tracing to trace async operations.

my code looks like:
```
public async Task DoSomething() {  
  using var scope = _tracer.BuildActiveSpan("open-tracing");  
  await _repo.DoSomething()  
}
```
After removing await - you will not be able to measure execution.
