### ISSUE TITLE
Warning inside query syntax

### ISSUE THREAD

**Issue by TheSilvermind** [semihokur/AsyncFixer#11]
Is it possible to disable warnings inside query syntax?

For example:

```
var query = from person in db.Persons
            select new
            {
                person.Id,
                roles = db.Roles.Where(r => r.PersonId == person.Id).ToList()
            };

var personsWithRoles = await query.ToListAsync();
```

It complains about `db.Roles.Where(r => r.PersonId == person.Id).ToList()`.

> AsyncFixer02	ToListAsync should be used instead of ...ToList

It is practically undoable to make the inner delegate expression async and as far as I know, ToListAsync cannot be translated to an sql statement.

**Comment by semihokur** [comment]
Thanks for reporting it. Yes, it is indeed a false-positive. I just created the PR #12.
