### ISSUE TITLE
Question: How to fix this AsyncFixer03 issue?

### ISSUE THREAD

**Issue by ryanbuening** [semihokur/AsyncFixer#16]
I have the following logic in my Blazor app. How could I resolve this AsyncFixer03 issue?

![image](https://user-images.githubusercontent.com/812974/113928709-22007300-97bd-11eb-9f20-f75f812ffa3d.png)

```
protected override void OnInitialized()
{
    _appState.StateChanged += async (Source, Property) => await AppState_StateChanged(Source, Property);
}
```

```
// StateChanged is an event handler that takes a component and a string to denote which property changed
public event Action<ComponentBase, string> StateChanged;
```

**Comment by gcstarr** [comment]
Having the same issue; event handlers require a void return type.

```csharp
AppDomain.CurrentDomain.ProcessExit += async (_, _) =>
            {
                shutdownStarted.Set();
                await shutdownComplete.WaitAsync();
            };
```

Could we get a way to suppress these warning individually via comment?

**Comment by semihokur** [comment]
Sorry about looking into this so late! I just fixed it and v1.6.1 will have the fix. I hope to release that in a week.

**Comment by mosoftwareenterprises** [comment]
Hi @semihokur any news on this fix being released?
Thanks for a great project, it is very helpful.

**Comment by Luk164** [comment]
It is 2025 and the fix is still not released
