### ISSUE TITLE
issue with latest version

### ISSUE THREAD

**Issue by goleafs** [semihokur/AsyncFixer#17]
seeing these errors with the latest version of AsynFixer 1.5.1 and NetAnalyzers 5.0.3

Error AD0001: Analyzer 'AsyncFixer.UnnecessaryAsync.UnnecessaryAsyncAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEAssemblySymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol'

**Comment by SeriousM** [comment]
Hi, is there an update to this issue? It's happening in our project and it's bugging our devs...

**Comment by semihokur** [comment]
Looking at it, but an example would be great.

**Comment by semihokur** [comment]
Could not find anything wrong given that we do not have any implicit or explicit casting for the symbols. This might be due to a bug in the Roslyn APIs. The repro example would be nice to confirm this. Then, I can try updating Roslyn dependencies to see whether it mitigates the crash.

**Comment by lupusbytes** [comment]
I am having the exact same issue.
I can't seem to replicate it in a simpler way, so I'll just show exactly how I'm triggering the error.

```
        [FunctionName(nameof(SubscribeToOrders))]
        public async Task SubscribeToOrders(
            [SignalRTrigger(HubName, "messages", nameof(SubscribeToOrders), ConnectionStringSetting = "AppSettings:SignalRConnection")] InvocationContext invocationContext,
            [SignalRParameter] SubscribeToOrdersParameters parameters)
        {
            var groupManager = await invocationContext.GetGroupsAsync();

            var tasks = parameters.OrderIds.Select(x => groupManager.AddToGroupAsync(invocationContext.ConnectionId, $"order-{x}"));

            await Task.WhenAll(tasks);
        }
```

My workaround is to write it like this, and no errors show.
```
            var groupManager = await invocationContext.GetGroupsAsync();

            var tasks = new List<Task>();
            foreach (var orderId in parameters.OrderIds)
            {
                tasks.Add(groupManager.AddToGroupAsync(invocationContext.ConnectionId, $"order-{orderId}"));
            }

            await Task.WhenAll(tasks);
```

The error does not show the correct line or file.
File is CSC and line is 1.

**Comment by semihokur** [comment]
Thank you for the example. I could not repro it. Because the problem is related to the semantic model and symbol table, I need something compilable. Is that code snippet from a public Github repo?

**Comment by lupusbytes** [comment]
No it's not public unfortunately. When I get some spare time, I will create a compilable repository with just this code, so you can clone it.

**Comment by semihokur** [comment]
Great, thank you!

**Comment by lupusbytes** [comment]
https://github.com/lupusbytes/AsyncFixerBugExample

Let me know if this works for you

**Comment by lupusbytes** [comment]
Any progress on this issue ?

**Comment by fl-int** [comment]
I'm facing the same error with my code as well. Is there any workaround? Will this be fixed?

**Comment by devedse** [comment]
I'm facing the same issue. Any plans to fix this?
