### ISSUE TITLE
Using declaration treated differently to using blocks

### ISSUE THREAD

**Issue by PCavan** [semihokur/AsyncFixer#18]
A using block containing an await is correctly identified as needing async-await to be present.

```
public async Task DoSomething1()
{
  using (var disposable = new Disposable())
  {
    await Task.Delay(1000);
  }
}
```

A semantically identical using declaration, however, is not - AsyncFixer suggests the removal of async-await from this:

```
public async Task DoSomething2()
{
  using var disposable = new Disposable();
  await Task.Delay(1000);
}
```

This is an incorrect suggestion because `disposable` will be disposed at the end of `DoSomething2` and must therefore wait for `Task.Delay` to finish, as is correctly identified in `DoSomething1`

**Comment by semihokur** [comment]
Forgot to close this one. Thanks to @marcelolynch, this got fixed.
