### ISSUE TITLE
No violation for async void in Action

### ISSUE THREAD

**Issue by Piedone** [semihokur/AsyncFixer#2]
Consider the following code:

```csharp
public static class Class1
{
    public static void Do()
    {
        Process(async input => await ProcessAsync());
    }
 
    private static void Process(Action<int> action)
    {
        action(12);
    }
 
    private static Task ProcessAsync()
    {
        return Task.CompletedTask;
    }
}
```

This doesn't report the async void delegate in Do() though it violates AsyncFixer03. In e-mail Semih confirmed this being a bug indeed.

**Comment by Piedone** [comment]
If I'm looking into contributing a fix for this, how should I start tackling it? It seems to me that `AsyncVoidAnalyzer` would contain the fix, and `AsyncVoidTests` corresponding tests. I don't think such a bug in the analyzed code can be automatically fixed so I wouldn't touch `AsyncVoidFixer `. How does this sound?

**Comment by semihokur** [comment]
The fixer will be triggered for each reported issue by the analyzer. That's why we should modify the fixer not to proceed with async-void delegates. I have some simple code changes to find the most common type of async-void delegates: https://github.com/semihokur/AsyncFixer/pull/5

**Comment by Piedone** [comment]
Thank you!

**Comment by semihokur** [comment]
merged!
