### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by ryanbuening** [semihokur/AsyncFixer#21]
Was wondering if there are plans to update this extension for VS 2022? Migration guide can be found here: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension

**Comment by SijyKijy** [comment]
@ryanbuening Update for VS 2022 here:
https://github.com/nbduong/AsyncFixer

**Comment by ryanbuening** [comment]
@SijyKijy is all future development happening on that fork?

**Comment by SijyKijy** [comment]
@ryanbuening
> @SijyKijy is all future development happening on that fork?

No. I suspect @semihokur gave up on development, so a fork was made

**Comment by semihokur** [comment]
No, I was just super busy with life and work :) I added the support for VS 2022, and I will upload the extension soon with some extra improvements.

**Comment by semihokur** [comment]
I published it in the VS gallery: https://marketplace.visualstudio.com/items?itemName=SemihOkur.AsyncFixer2022

It is v1.5.2 and I will be publishing v1.6 with more improvements in a week or so.
