### ISSUE TITLE
AsyncFixer01 does not take await foreach into account

### ISSUE THREAD

**Issue by Dampypena** [semihokur/AsyncFixer#22]
The AsyncFixer01 makes suggestions without taking into account the possible `await foreach` in the method.

For example, this method is flagged by the AsyncFixer01 warning:
```c#
public async Task MyFunction()
{
   await foreach(var i in GetAsync(query).ConfigureAwait(false))
   {
      ...
   }

   await DoSomethingAsync().ConfigureAwait(false);
}
```

If we apply the automatic suggestion, we get this:
```c#
public Task MyFunction()
{
   await foreach(var i in GetAsync(query).ConfigureAwait(false))
   {
      ...
   }

   return DoSomethingAsync().ConfigureAwait(false);
}
```

As you can see, the `async` keyword is removed although we still have the `await` keyword before the `foreach` which causes a compilation error.

**Comment by semihokur** [comment]
Thanks for reporting, I just fixed it. The fix will be included in v1.6.1 that will be released in a week.
