### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by waynebrantley** [semihokur/AsyncFixer#23]
I know you did a preview, but the current download only supports 2019.
@semihokur you had talked about a 1.6 with more improvements back in July - is there a possibility of an update for 2022 anytime soon?

@SijyKijy are you just using your repo - building locally and installing, because I did not see a publish.  If no plans I may just do that?

**Comment by SijyKijy** [comment]
Sure

**Comment by waynebrantley** [comment]
@SijyKijy your repo is all from preview versions and such too.  Fyi

**Comment by jzabroski** [comment]
@semihokur @marcelolynch Do you need help creating a VS2022 version ?

It seems like a GitHub Action to build the VSIX and upload it to the Visual Studio gallery would be ideal. But at least a way to try the preview versions from nuget.org at the package level.

**Comment by jzabroski** [comment]
Spoke to @semihokur on Twitter - he noted support is published here: https://marketplace.visualstudio.com/items?itemName=SemihOkur.AsyncFixer2022

I pointed out to him the nuget package doesnt seem to be up to date. https://www.nuget.org/packages/AsyncFixer/

**Comment by semihokur** [comment]
Sorry about my late reply. v1.5.1 package actually works in VS2022. Please let me know if you have any issues with v1.5.1 in VS2022.

This [commit ](https://github.com/semihokur/AsyncFixer/commit/801fde9911775b163e8e61333f22aaadb890a4e6) was just adding VS2022 support for the vsix extension.

**Comment by jzabroski** [comment]
Ah... I made an illogical leap. Sorry. Should have tested it.

**Comment by semihokur** [comment]
Just published a new release: https://github.com/semihokur/AsyncFixer/releases/tag/v1.6.0
