### ISSUE TITLE
Analyzer links should be directed to the docs

### ISSUE THREAD

**Issue by EddyHaigh** [semihokur/AsyncFixer#24]
When using the nuget package and there are issue if you want to take a look at the issue in more depth you can click the link on the anaylzer code. These codes current direct to a bing.dev url but should really link to the docs/the repo.

Heres an example of the link currently seen in visual studio 2022
![image](https://user-images.githubusercontent.com/23223991/155205604-5359d5f6-140e-4882-b2d6-f41505bb6e5c.png)

**Comment by semihokur** [comment]
Thank you for reporting. I added a link to the repo for now.
