### ISSUE TITLE
AsyncFixer01: false positive with ValueTask awaited in method returning Task

### ISSUE THREAD

**Issue by egil** [semihokur/AsyncFixer#25]
This simple example from a Blazor (.NET 6) triggers the `AsyncFixer01` analyzer on the method `OnAfterRenderAsync`:

```c#
protected override async Task OnAfterRenderAsync(bool firstRender)
        => await DoStuff();

private async ValueTask DoStuff() { ... }
```

Changing `OnAfterRenderAsync` as suggested causes a compiler error.

```c#
protected override Task OnAfterRenderAsync(bool firstRender)
        => DoStuff();
```

The two errors are:

1. CS0029 Cannot implicitly convert type 'System.Threading.Tasks.ValueTask' to 'System.Threading.Tasks.Task'` 
2. CA2012 ValueTask instances returned from method calls should be directly awaited, returned, or passed as an argument to another method call. Other usage, such as storing an instance into a local or a field, is likely an indication of a bug, as ValueTask instances must only ever be consumed once.

**Comment by semihokur** [comment]
Thanks for reporting. Could you please let me know which version you are using? I could not get a repro.

**Comment by egil** [comment]
Sorry, should have version info:

AsyncFixer: 1.5.1
.NET: 6.0.202

Analyzer settings enabled:

```
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
```

**Comment by semihokur** [comment]
Could you please try it with the latest version:  https://github.com/semihokur/AsyncFixer/releases/tag/v1.6.0

**Comment by egil** [comment]
It seems to be solved. Thank you!
