### ISSUE TITLE
Incorrect AsyncFixer01 violation for Task<T> if T is covariant

### ISSUE THREAD

**Issue by Piedone** [semihokur/AsyncFixer#3]
Consider the following code:

```csharp
    public class Test
    {
        public async Task<IEnumerable<string>> CreateEnumerableAsync() =>
            await CreateListAsync();

        public Task<IList<string>> CreateListAsync() => Task.FromResult(new List<string>() as IList<string>);
    }
```

`CreateEnumerableAsync()` violates AsyncFixer01 with "The method 'CreateEnumerableAsync' does not need to use async/await.". While at a first glance this seems correct as after `await CreateListAsync()` there's nothing else done, and `IList<string>` can be cast to `IEnumerable<string>`, however, since `Task<IList<string>>` can NOT be cast to `Task<IEnumerable<string>>` the code without `asnyc` and `await` causes a compiler error:

```csharp
        public Task<IEnumerable<string>> CreateEnumerableAsync() =>
            CreateListAsync();
```

This is because `Task<T>`, on the contrary to the `T` in question above, [is not covariant](https://stackoverflow.com/questions/30996986/why-is-taskt-not-co-variant).

**Comment by semihokur** [comment]
Thanks for reporting it. When I added the support for expression-bodied members, I  forgot to check the implicit casting. Feel free to look at the PR: 
https://github.com/semihokur/AsyncFixer/pull/4

**Comment by Piedone** [comment]
Thank you for this too!

**Comment by Piedone** [comment]
Thank you for your quick work on both issues!

**Comment by semihokur** [comment]
no worries. I just published a new release in the NuGet and VSIX gallery:
https://github.com/semihokur/AsyncFixer/releases/tag/v1.4.1

**Comment by Piedone** [comment]
Thank you, both bugs are fixed though I did find a new case :).
