### ISSUE TITLE
Conflicting AsyncFixer01 on use of FluentAssertions ThrowAsync

### ISSUE THREAD

**Issue by rcollette** [semihokur/AsyncFixer#33]
I get a conflicting report that await is not necessary on the last line of this code snippet, but then the compiler complains if I remote the await.

```c#
#pragma warning disable AsyncFixer01
    [Fact]
    public async Task CreateUserProfileAsync_WhenNotInBlockListAndActorIdNotAssigned_ThrowsError()
    {
        // Arrange
        CreateUserProfileModel createUserProfileModel = CreateUserProfileModel();
        CreateUserRequestDto createUserRequestDto = new();
        User user = CreateUser();
        _userClient.Setup(s => s.CreateUserAsync(createUserRequestDto)).ReturnsAsync(user);

        // Act
        Func<Task> func =  ()=> _service.CreateUserProfileAsync(createUserProfileModel);

        // Assert
       // Issue is with the following line.
        await func.Should().ThrowExactlyAsync<InvalidOperationException>().WithMessage("The actorId property was not stored on the user profile for user with login user@acme.com ");
    }
#pragma warning restore AsyncFixer01
```

**Comment by 0liver** [comment]
When you remove the `await`, you'll also need to remove the `async` in the method signature.

That works for me.

**Comment by rcollette** [comment]
`.WithMessage` is an async function.  If I remove the await, and the async from the test method, I get another error.

```
MA0134: Observe result of async calls
VSTHRD110: Observe the awaitable result of this method call by awaiting it, assigning to a variable, or passing it to another method.
```
![image](https://github.com/semihokur/AsyncFixer/assets/136476/8a2f3541-4f76-4d43-b3d9-b8394eb03fe5)

**Comment by 0liver** [comment]
How about returning the value (`Task`) then?

**Comment by rcollette** [comment]
🤦 So sorry.  Part of this is from working in the JavaScript world where having test functions returning promises is generally a nightmare vs. using async/await.   I think I automatically default to using async/await on .NET test methods, thinking that the test framework is just going to skip past the test without waiting for the result.

Thanks again.

**Comment by 0liver** [comment]
Happy to help!
