### ISSUE TITLE
error AD0001: Analyzer 'AsyncFixer.AsyncCallInsideUsingBlock.AsyncCallInsideUsingBlockAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by credfeto** [semihokur/AsyncFixer#6]
Haven't tracked this down to a specific method yet - this just started happening when updating from 1.3.0 to 1.4.0.

It doesn't happen on all projects using it just some and those ones are the larger projects where there are thousands of calls.

is there anything I can do to get more detail to help track this down?

**Comment by semihokur** [comment]
Did you see the error with the VSIX or NuGet package?

I very likely fixed the issue. Could you please try with v1.4.1: 
https://github.com/semihokur/AsyncFixer/releases/tag/v1.4.1

**Comment by credfeto** [comment]
It was with the Nuget package.

Looks like its fixed so far with the new version going through some other solutions to see if its also fixed there.

Thanks
